[package]
name = "miners"
version = "0.0.0-beta.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = ["net", "packets"]
net = ["dep:miners-net"]
packets = ["dep:miners-packets"]

[dependencies]
miners-packets = { path = "packets", version = "0.0.0-beta.0", optional = true }
miners-net = { path = "net", version = "0.0.0-beta.0", optional = true }

[workspace]
members = [
  "packets",
  "packets/derive",
  "packets/traits",
  "encoding",
  "net"
]
