[package]
name = "miners"
version = "0.0.0-beta.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
protocol = { path = "protocol", package = "miners-protocol" }

[workspace]
members = [
  "protocol",
  "protocol-derive"
]
