[package]
name = "miners"
version = "0.0.0-beta.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
net = ["dep:miners-net"]
packets = ["dep:miners-packets"]
auth = ["dep:miners-auth"]
chat = ["dep:miners-chat"]
default = ["net", "packets", "auth"]

[dependencies]
miners-packets = { path = "packets", version = "0.0.0-beta.0", optional = true }
miners-net = { path = "net", version = "0.0.0-beta.0", optional = true }
miners-auth = { path = "auth", version = "0.0.0-beta.0", optional = true}
miners-chat = { path = "chat", version = "0.0.0-beta.0", optional = true}

[workspace]
members = [
  "packets",
  "packets/derive",
  "net",
  "auth", 
  "chat"
]
