[package]
name = "miners-packets"
version = "0.0.0-beta.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
packets-derive = { path = "derive", package = "miners-packets-derive", version = "0.0.0-beta.0" }
uuid = "1.1.2"
