[package]
name = "miners-to-static"
version = "0.0.0-beta.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
uuid = { version = "1.1.2", optional = true }

[features]
default = ["uuid"]