[package]
name = "net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
cfb8 = "0.8.1"
aes = "0.8.1"
flate2 = "1.0.24"
miners-protocol = { version = "0.0.0-beta.0", optional = true, path = "../protocol" }

[features]
default = ["protocol"]
protocol = ["miners-protocol"]
